#!/usr/bin/env bash
# Configures localhost and facebook.com to use the required IP addresses.

awk '
/^[[:space:]]*127\.0\.0\.1[[:space:]]+localhost([[:space:]]|$)/ {
    print "127.0.0.2 localhost"
    next
}
/^[[:space:]]*[0-9.]+[[:space:]]+facebook\.com([[:space:]]|$)/ {
    next
}
{ print }
END {
    print "8.8.8.8 facebook.com"
}
' /etc/hosts > /tmp/hosts.new

cat /tmp/hosts.new > /etc/hosts
rm -f /tmp/hosts.new